
language: objective-c
osx_image: xcode9

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

notifications:
  email: false

before_install:

    - env
    - locale
    - xcpretty --version
    - xcodebuild -version
    - xcodebuild -showsdks

script:
    - set -o pipefail
    - xcodebuild clean build -workspace RetriableAFNetworking.xcworkspace -scheme 'RetriableAFNetworking iOS' -sdk iphonesimulator PLATFORM_NAME=iphonesimulator -configuration Debug | xcpretty
    - xcodebuild clean build -workspace RetriableAFNetworking.xcworkspace -scheme 'RetriableAFNetworking iOS Example' -sdk iphonesimulator PLATFORM_NAME=iphonesimulator -configuration Debug | xcpretty
    - xcodebuild clean build -workspace RetriableAFNetworking.xcworkspace -scheme 'RetriableAFNetworking watchOS' -sdk watchsimulator -configuration Debug | xcpretty
    - xcodebuild clean build -workspace RetriableAFNetworking.xcworkspace -scheme 'RetriableAFNetworking watchOS Example' -sdk watchsimulator -configuration Debug | xcpretty
    - xcodebuild clean build -workspace RetriableAFNetworking.xcworkspace -scheme 'RetriableAFNetworking tvOS'  -sdk appletvsimulator -configuration Debug | xcpretty
    - xcodebuild clean build -workspace RetriableAFNetworking.xcworkspace -scheme 'RetriableAFNetworking tvOS Example'  -sdk appletvsimulator -configuration Debug | xcpretty
    - xcodebuild clean build -workspace RetriableAFNetworking.xcworkspace -scheme 'RetriableAFNetworking macOS' -sdk macosx -configuration Debug | xcpretty
    - xcodebuild clean build -workspace RetriableAFNetworking.xcworkspace -scheme 'RetriableAFNetworking macOS Example' -sdk macosx -configuration Debug | xcpretty
